language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  - directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: ./gradlew build
after_success:
  ./gradlew uploadArchives
env:
 global:
   - ORG_GRADLE_PROJECT_ossSnapshotRepositoryUrl=https://oss.sonatype.org/content/repositories/snapshots/
   - secure: "psApg+GAO6HNCVugolA1t6Mx5EA2zt4zsDSnZ4q93irSK0lVmu49cfkGfAkEnPJwLFzxox4faf7cPABwcjzx/xj5vSSrJKpwvKAYPVv6MjoeiXFIGtMZvf1cV8VNyMaYSK/U/CZByg9abAEbzhOoIto8uflWt87TqskLlKNz7orb5jL3ySYV0JoA5545Fm0V/mBej4a02D7X1zoMsbnJDVrUdlKpMNCb8bSJ32WENuooh4AvFqwaBlwfPgXHUMFMQ8Hx/X8ovWTm87Wq6t/EW/BjXUftt5x/YiO2odsM6xQ/PZU6jEzSetwKUcQ4e6DHiEyIk5Na68i/iPDO/gLbqhW1l2dlEiyZS+yToUmHObyEANlaaIz1j40mHePrm6ClgNXD1IevbMDnzqQbFAbGTgc2ukp5c8vzT14xmlJIQU3qz2H4f/CyDRA3Z6e7M6GxfES6J1VHsqB+cpq4hkmEra7MZ+I9z7Yi5T3uV83Sj1mrZeh7wrGTGFovpQ8mrpEFji3+c+WMCnRLxNuQqHpesSSULlD4h4GZIL76sDjbWgEyeBEN32XriTz8wv0DE6IzZCaWpvPsOH7NMDNcnUzhZmK2VJNxOmh5f3628FsV9X61mSmPtsTwZPFfdixZzBuaLzkbmFKBQieZ+2wm2c/2mXF+YXJYT3yrrDBRELjsXEM="
   - secure: "JUrV+0pBF0mvPc3jx62lkghNnp3aRwAVTgVcsL1CFa1++DgNK4wvmrlW7HybvMYPCR+yeKg8B0knaLJpVEzqjYPV7JSbcWmqZtKwZbCh6ODpY1WUZAzTWSBr71ufyi0K94r/ComcoBBoATgZljx1Prk8HpYgCbduJTmYbgGnG3O7JxfyY4EvcwiCW/EBAnHM+0UgdpVIP0rjt0z7eOdoPhQcc1KnemZ2R49FdkrslkqJtrjq/1SB8GIXjSQPuensW4ne2pIphdGtkhMsXV1q6SwjgXNtOQmQclEDo30A1AvvzUweihVZaf599A2CaJMfkywjEMQjHSuSxKC7BR1wKwkB5KqeI6nmYlGLNN5gVXqqKmuBLzpgLen2TKUVs9+2NF6CPbOl3AyXfFsoECVtF4ek/6ABlDOkE2uTCnAl1VjqWsEjyprZooujVpRdl/xxTjwn/V1n29kFKBJO53RDrWeZQoLUZUqr5P3a7mTzjmAtzFE3DK0Y7+Lg1U/Ey3F/YhURHOYiuLHKLSeZlp7lcPV/lo3Z19+LDYclbmVjT+JsDgZ2L5FHsf2YOdaVt+Jv5W7nXHyVz84ZFvWH2SjGbwAFhFMmtl8zWzfnS6SH/I4vz+nmGgHodQJKUeVIMYYx7vA+ingml61HWm3S5kNP60mEtbYRfX3JGd8u75mMWTw="
